spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trim?serverTimezone=UTC
    username: admin
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true  # SQL 포맷 정렬 여부
        show-sql: true

  redis:
    data:
      host: localhost
      port: 6379

# 서버 포트 설정 (기본 포트 변경 시)
server:
  port: 8080

# 로깅 레벨 설정 (필요 시)
logging:
  level:
    root: info
    org.springframework.web: debug

app:
  jwt:
    secret: 88c6c135a1457c40092a793f1fbe39cdf71423ad2b26670231420512a54273f6