spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trim
    username: root
    password: tmddud34kudn!!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true  # SQL 포맷 정렬 여부
        show-sql: true

  redis:
    data:
      host: localhost
      port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: { YOUR_CLIENT_ID }
            client-secret: { YOUR_CLIENT_SECRET }
            scope: profile,email
          naver:
            client-id: { YOUR_CLIENT_ID }
            client-secret: { YOUR_CLIENT_SECRET }
            scope: name,email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          kakao:
            client-id: { YOUR_CLIENT_ID }
            client-secret: { YOUR_CLIENT_SECRET }
            scope: profile_nickname,account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_post

        provider:
          google:
            authorization-uri: "서비스 로그인 창 주소"
            token-uri: "토큰 발급 서버 주소"
            user-info-uri: "사용자 정보 획득 주소"
            user-name-attribute: "응답 데이터 변수"
          naver:
            authorization-uri: "서비스 로그인 창 주소"
            token-uri: "토큰 발급 서버 주소"
            user-info-uri: "사용자 정보 획득 주소"
            user-name-attribute: "응답 데이터 변수"
          kakao:
            authorization-uri: "서비스 로그인 창 주소"
            token-uri: "토큰 발급 서버 주소"
            user-info-uri: "사용자 정보 획득 주소"
            user-name-attribute: "응답 데이터 변수"

# 서버 포트 설정 (기본 포트 변경 시)
server:
  port: 8080

# 로깅 레벨 설정 (필요 시)
logging:
  level:
    root: info
    org.springframework.web: debug

app:
  jwt:
    secret: 88c6c135a1457c40092a793f1fbe39cdf71423ad2b26670231420512a54273f6